export const followers = [
  {
    login: "gustavogbi",
    id: 11924716,
    node_id: "MDQ6VXNlcjExOTI0NzE2",
    avatar_url: "https://avatars.githubusercontent.com/u/11924716?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/gustavogbi",
    html_url: "https://github.com/gustavogbi",
    followers_url: "https://api.github.com/users/gustavogbi/followers",
    following_url: "https://api.github.com/users/gustavogbi/following{/other_user}",
    gists_url: "https://api.github.com/users/gustavogbi/gists{/gist_id}",
    starred_url: "https://api.github.com/users/gustavogbi/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/gustavogbi/subscriptions",
    organizations_url: "https://api.github.com/users/gustavogbi/orgs",
    repos_url: "https://api.github.com/users/gustavogbi/repos",
    events_url: "https://api.github.com/users/gustavogbi/events{/privacy}",
    received_events_url: "https://api.github.com/users/gustavogbi/received_events",
    type: "User",
    site_admin: false
  },
  {
    login: "danielrcoura",
    id: 21161221,
    node_id: "MDQ6VXNlcjIxMTYxMjIx",
    avatar_url: "https://avatars.githubusercontent.com/u/21161221?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/danielrcoura",
    html_url: "https://github.com/danielrcoura",
    followers_url: "https://api.github.com/users/danielrcoura/followers",
    following_url: "https://api.github.com/users/danielrcoura/following{/other_user}",
    gists_url: "https://api.github.com/users/danielrcoura/gists{/gist_id}",
    starred_url: "https://api.github.com/users/danielrcoura/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/danielrcoura/subscriptions",
    organizations_url: "https://api.github.com/users/danielrcoura/orgs",
    repos_url: "https://api.github.com/users/danielrcoura/repos",
    events_url: "https://api.github.com/users/danielrcoura/events{/privacy}",
    received_events_url: "https://api.github.com/users/danielrcoura/received_events",
    type: "User",
    site_admin: false
  },
  {
    login: "a3X3k",
    id: 52845731,
    node_id: "MDQ6VXNlcjUyODQ1NzMx",
    avatar_url: "https://avatars.githubusercontent.com/u/52845731?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/a3X3k",
    html_url: "https://github.com/a3X3k",
    followers_url: "https://api.github.com/users/a3X3k/followers",
    following_url: "https://api.github.com/users/a3X3k/following{/other_user}",
    gists_url: "https://api.github.com/users/a3X3k/gists{/gist_id}",
    starred_url: "https://api.github.com/users/a3X3k/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/a3X3k/subscriptions",
    organizations_url: "https://api.github.com/users/a3X3k/orgs",
    repos_url: "https://api.github.com/users/a3X3k/repos",
    events_url: "https://api.github.com/users/a3X3k/events{/privacy}",
    received_events_url: "https://api.github.com/users/a3X3k/received_events",
    type: "User",
    site_admin: false
  }
];
